hangman_words = [
    "apple", "banana", "orange", "grape", "kiwi",
    "mango", "peach", "pear", "plum", "lemon",
    "cherry", "berry", "melon", "apricot", "fig",
    "date", "guava", "lime", "lychee", "olive",
    "pumpkin", "squash", "turnip", "carrot", "potato",
    "onion", "garlic", "celery", "spinach", "broccoli",
    "cauliflower", "cucumber", "eggplant", "pepper", "tomato",
    "lettuce", "mushroom", "radish", "beet", "corn",
    "rice", "wheat", "barley", "oat", "rye",
    "bread", "pasta", "pizza", "burger", "sandwich",
    "soup", "salad", "steak", "chicken", "fish",
    "pork", "beef", "lamb", "turkey", "duck",
    "goose", "rabbit", "deer", "horse", "cow",
    "dog", "cat", "bird", "fish", "snake",
    "lizard", "turtle", "frog", "toad", "insect",
    "spider", "ant", "bee", "fly", "butterfly",
    "moth", "beetle", "worm", "snail", "slug",
    "tree", "flower", "grass", "leaf", "root",
    "branch", "forest", "mountain", "river", "ocean",
    "lake", "desert", "island", "valley", "cave",
    "cloud", "rain", "snow", "wind", "storm",
    "sun", "moon", "star", "planet", "galaxy",
    "universe", "time", "space", "light", "dark",
    "color", "shape", "sound", "music", "art",
    "book", "movie", "game", "sport", "car",
    "train", "plane", "boat", "ship", "house",
    "building", "city", "country", "world", "person",
    "name", "face", "hand", "foot", "body",
    "head", "eye", "ear", "nose", "mouth",
    "hair", "heart", "brain", "blood", "bone",
    "dream", "idea", "thought", "feeling", "emotion",
    "love", "hate", "joy", "sadness", "anger",
    "fear", "surprise", "peace", "war", "life",
    "death", "birth", "marriage", "divorce", "work",
    "school", "college", "university", "job", "money",
    "computer", "internet", "phone", "television", "radio",
    "camera", "picture", "photo", "music", "song",
    "dance", "play", "watch", "listen", "read",
    "write", "speak", "learn", "teach", "travel",
    "explore", "discover", "create", "destroy", "begin",
    "end", "win", "lose", "find", "lose",
    "remember", "forget", "understand", "believe", "know",
    "think", "feel", "see", "hear", "touch",
    "taste", "smell", "move", "stop", "go",
    "come", "stay", "leave", "give", "take",
    "use", "make", "do", "say", "ask",
    "answer", "help", "need", "want", "like",
    "dislike", "try", "succeed", "fail", "live",
    "die", "exist", "happen", "change", "continue",
    "start", "finish", "open", "close", "turn",
    "walk", "run", "jump", "swim", "fly",
    "drive", "ride", "climb", "fall", "break",
    "fix", "build", "destroy", "protect", "attack",
    "defend", "fight", "win", "lose", "survive",
    "escape", "hide", "seek", "find", "lose",
    "search", "discover", "invent", "create", "design",
    "develop", "improve", "reduce", "increase", "grow",
    "shrink", "expand", "contract", "connect", "disconnect",
    "combine", "separate", "divide", "multiply", "subtract",
    "add", "remove", "replace", "exchange", "trade",
    "sell", "buy", "borrow", "lend", "give",
    "receive", "accept", "refuse", "agree", "disagree",
    "support", "oppose", "lead", "follow", "control",
    "obey", "command", "request", "demand", "suggest",
    "advise", "warn", "threaten", "promise", "apologize",
    "forgive", "punish", "reward", "praise", "criticize",
    "judge", "evaluate", "analyze", "interpret", "explain",
    "describe", "define", "compare", "contrast", "relate",
    "connect", "organize", "classify", "categorize", "group",
    "order", "arrange", "sequence", "structure", "form",
    "create", "build", "construct", "produce", "generate",
    "manufacture", "assemble", "install", "operate", "maintain",
    "repair", "improve", "develop", "advance", "progress",
    "evolve", "transform", "change", "modify", "adjust",
    "adapt", "convert", "switch", "transfer", "move",
    "transport", "carry", "deliver", "send", "receive",
    "communicate", "inform", "tell", "show", "explain",
    "describe", "demonstrate", "prove", "convince", "persuade",
    "influence", "affect", "impact", "cause", "result",
    "prevent", "avoid", "protect", "defend", "attack",
    "resist", "overcome", "achieve", "succeed", "fail",
    "learn", "study", "research", "investigate", "discover",
    "explore", "experience", "practice", "develop", "improve",
    "master", "perfect", "excel", "achieve", "accomplish",
    "realize", "fulfill", "attain", "obtain", "acquire",
    "gain", "earn", "win", "lose", "find",
    "discover", "invent", "create", "design", "develop",
    "produce", "generate", "manufacture", "assemble", "install",
    "operate", "maintain", "repair", "improve", "develop",
    "advance", "progress", "evolve", "transform", "change",
    "modify", "adjust", "adapt", "convert", "switch",
    "transfer", "move", "transport", "carry", "deliver",
    "send", "receive", "communicate", "inform", "tell",
    "show", "explain", "describe", "demonstrate", "prove",
    "convince", "persuade", "influence", "affect", "impact",
    "cause", "result", "prevent", "avoid", "protect",
    "defend", "attack", "resist", "overcome", "achieve",
    "succeed", "fail", "learn", "study", "research",
    "investigate", "discover", "explore", "experience", "practice",
    "develop", "improve", "master", "perfect", "excel",
    "achieve", "accomplish", "realize", "fulfill", "attain",
    "obtain", "acquire", "gain", "earn", "win",
    "lose", "find", "discover", "invent", "create",
    "design", "develop", "produce", "generate", "manufacture",
    "assemble", "install", "operate", "maintain", "repair",
    "improve", "develop", "advance", "progress", "evolve",
    "transform", "change", "modify", "adjust", "adapt",
    "convert", "switch", "transfer", "move", "transport",
    "carry", "deliver", "send", "receive", "communicate",
    "inform", "tell", "show", "explain", "describe",
    "demonstrate", "prove", "convince", "persuade", "influence",
    "affect", "impact", "cause", "result", "prevent",
    "avoid", "protect", "defend", "attack", "resist",
    "overcome", "achieve", "succeed", "fail", "learn",
    "study", "research", "investigate"]

    










